from argparse import ArgumentParser


class ParseArguments:
    @staticmethod
    def parse():
        parser = ArgumentParser()
        parser.add_argument("file", nargs="*")
        parser.add_argument("-C", action="store_true")
        parser.add_argument("-D", action="store_true")
        parser.add_argument("-l", "--level", type=int, default=18)
        parser.add_argument("-L", "--long", action="store_true", default=False)
        parser.add_argument("-B", "--block", action="store_true", default=False)
        parser.add_argument("-S", "--solid", action="store_true", default=False)
        parser.add_argument("-s", "--bs", type=int, default=20)
        parser.add_argument("-V", "--verify", action="store_true", default=False)
        parser.add_argument("-Q", "--quick-verify", action="store_true", default=False)
        parser.add_argument("-K", "--keep", action="store_true", default=False)
        parser.add_argument("-F", "--fix-padding", action="store_true", default=False)
        parser.add_argument("-p", "--parseCnmt", action="store_true", default=False)
        parser.add_argument("-P", "--alwaysParseCnmt", action="store_true", default=False)
        parser.add_argument("-t", "--threads", type=int, default=-1)
        parser.add_argument("-m", "--multi", type=int, default=4)
        parser.add_argument("-o", "--output")
        parser.add_argument("-w", "--overwrite", action="store_true", default=False)
        parser.add_argument("-r", "--rm-old-version", action="store_true", default=False)
        parser.add_argument("--rm-source", action="store_true", default=False)
        parser.add_argument("-x", "--extract", action="store_true")
        parser.add_argument("--extractregex", type=str, default="")
        parser.add_argument("--titlekeys", action="store_true", default=False)
        parser.add_argument("--undupe", action="store_true")
        parser.add_argument("--undupe-dryrun", action="store_true")
        parser.add_argument("--undupe-rename", action="store_true")
        parser.add_argument("--undupe-hardlink", action="store_true")
        parser.add_argument("--undupe-prioritylist", type=str, default="")
        parser.add_argument("--undupe-whitelist", type=str, default="")
        parser.add_argument("--undupe-blacklist", type=str, default="")
        parser.add_argument("--undupe-old-versions", action="store_true", default=False)
        parser.add_argument("-c", "--create")
        parser.add_argument("--machine-readable", action="store_true", default=False)
        return parser.parse_args()
